# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/mp/wcc_demo/python_work/pyqt/pyqt_osc/main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 751, 541))
        self.groupBox.setObjectName("groupBox")
        self.btn_reset = QtWidgets.QPushButton(self.centralwidget)
        self.btn_reset.setGeometry(QtCore.QRect(880, 460, 121, 31))
        self.btn_reset.setObjectName("btn_reset")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(800, 400, 251, 29))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.radiobtn_ch1 = QtWidgets.QRadioButton(self.splitter_3)
        self.radiobtn_ch1.setObjectName("radiobtn_ch1")
        self.radiobtn_ch2 = QtWidgets.QRadioButton(self.splitter_3)
        self.radiobtn_ch2.setObjectName("radiobtn_ch2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(760, 290, 361, 100))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.dial_ch1_amp = QtWidgets.QDial(self.splitter_4)
        self.dial_ch1_amp.setMinimum(1)
        self.dial_ch1_amp.setMaximum(10)
        self.dial_ch1_amp.setSingleStep(2)
        self.dial_ch1_amp.setObjectName("dial_ch1_amp")
        self.dial_ch2_amp = QtWidgets.QDial(self.splitter_4)
        self.dial_ch2_amp.setMaximum(5)
        self.dial_ch2_amp.setObjectName("dial_ch2_amp")
        self.dial_time_scale = QtWidgets.QDial(self.splitter_4)
        self.dial_time_scale.setMinimum(1000)
        self.dial_time_scale.setMaximum(10000)
        self.dial_time_scale.setSingleStep(100)
        self.dial_time_scale.setObjectName("dial_time_scale")
        self.splitter_8 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_8.setGeometry(QtCore.QRect(780, 60, 281, 91))
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label = QtWidgets.QLabel(self.splitter_7)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.splitter_7)
        self.label_2.setObjectName("label_2")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.cursor_ch1 = QtWidgets.QSlider(self.splitter_6)
        self.cursor_ch1.setOrientation(QtCore.Qt.Horizontal)
        self.cursor_ch1.setObjectName("cursor_ch1")
        self.cursor_ch2 = QtWidgets.QSlider(self.splitter_6)
        self.cursor_ch2.setOrientation(QtCore.Qt.Horizontal)
        self.cursor_ch2.setObjectName("cursor_ch2")
        self.splitter_9 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_9.setGeometry(QtCore.QRect(760, 170, 351, 81))
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.label_3 = QtWidgets.QLabel(self.splitter_9)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_9)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.dial_ch1_bais = QtWidgets.QDial(self.splitter_5)
        self.dial_ch1_bais.setMinimum(-10)
        self.dial_ch1_bais.setMaximum(10)
        self.dial_ch1_bais.setObjectName("dial_ch1_bais")
        self.dial_ch2_bais = QtWidgets.QDial(self.splitter_5)
        self.dial_ch2_bais.setMaximum(5)
        self.dial_ch2_bais.setObjectName("dial_ch2_bais")
        self.dial_time_bais = QtWidgets.QDial(self.splitter_5)
        self.dial_time_bais.setMaximum(1000)
        self.dial_time_bais.setSingleStep(100)
        self.dial_time_bais.setObjectName("dial_time_bais")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1121, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "display"))
        self.btn_reset.setText(_translate("MainWindow", "Reset"))
        self.radiobtn_ch1.setText(_translate("MainWindow", "ch1"))
        self.radiobtn_ch2.setText(_translate("MainWindow", "ch2"))
        self.label.setText(_translate("MainWindow", "t1"))
        self.label_2.setText(_translate("MainWindow", "t2"))
        self.label_3.setText(_translate("MainWindow", "Bais Setting"))

